name: "Ensure Error"

on:
  workflow_dispatch:
  push:
    paths:
      [
        "**.swift",
        ".github/workflows/ensure_error.yml"
      ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: sushichop/gha-swift-env@v1
        with:
          swift-version: '5.7.2'
      - run: "swift build --use-integrated-swift-driver"